sampling: # 采样配置
  sample_dir: ./data # 采样结果保存路径
  save_format: npz # 采样结果保存格式，可选值：csv, json, npz, mat
  # legacy: 不同类别分开文件夹，专门录制该动作的一段数据点，每个文件具有一个标签
  # nova: 一次录制的数据统一存储在一个文件中，每个数据点均有对应的标签
  save_type: nova
  sample_rate: 1000 # 采样频率，单位Hz
  batch_size: 50 # 每次采样的批量大小
  channels:
    count: 8
    # 通道名称列表，用于在 UI 展示和CSV存储header，长度多于 count 的部分无效，少于则使用默认 `CH<idx>` 命名
    names: ["CH1", "CH2", "CH3", "CH4", "CH5", "CH6", "CH7", "CH8"]

    source: review # 数据来源，可选值：esp32, review, generate # review: 回放已采样数据文件 # generate: 生成数据

preproc: # 采集时预处理配置
  enabled: true # 是否启用预处理
  methods: # 预处理方法列表，按顺序依次应用, 参数提供方式参见函数定义
    - type: overwave_filter # 去除突波
      params:
        win_len: 25 # 窗口长度，单位采样点
        method: var # 计算突波指标的方法，可选值：var, diff
        fill_with: kalman # 突波处数据填充方法，可选值：zero, mean, interp, kalman
        k: 5.0 # 突波检测阈值参数，数值越大越不敏感
        edge_cut: 1 # 边缘裁剪长度，单位采样点
    - type: bandpass # 带通滤波
      params:
        f1: 5 # 下限频率，单位Hz
        f2: 100 # 上限频率，单位Hz
        order: 6 # 滤波器阶数
    - type: notch # 工频陷波
      params:
        f0: 50.0 # 陷波频率，单位Hz
        Q: 30 # 品质因数

labeling: # 标签配置
  channels:
    count: 5 # 输出通道数
    names: ["thumb", "index", "middle", "ring", "pinky"] # 输出通道名称列表
  items:
    default: [1, 1, 1, 1, 1] # 默认标签
    fist: [0, 0, 0, 0, 0] # 拳头
    palm: [2, 2, 2, 2, 2] # 手掌
    ok: [0, 0, 2, 2, 2] # OK 手势
    peace: [0, 2, 2, 0, 0] # V 手势
  labels:
    - 收缩 
    - 放松
    - 舒张

exper: # 训练配置
  project: runs # 实验项目文件夹
  name: emgexp # 实验名称
  seed: 42 # 随机种子，确保实验可复现

  dataset:
    path:
      source: ./data # 数据源文件夹路径
      cache: # TODO
        enabled: true # 是否启用缓存，加快数据加载速度
        path: ./window/
    split: # 数据集划分比例，仅在 exper.path.val/test 为空时, 若非为空，则配置无效，并把对应 partio 添加到训练集
      train: 0.7
      val: 0.15
      test: 0.15
    window_size: 120 # 采样窗口大小，单位采样点
    overlap: 0.25 # 采样窗口*重叠*比例

  log:
    level: info # 日志等级，可选值：debug, info, warning, error, critical
    format: "[%(asctime)s][%(levelname)s]: %(message)s" # 日志格式

  train:
    batch_size: 32 # 训练批量大小
    epochs: 150 # 训练轮数
    device: auto # 训练设备，可选值：cpu, cuda, cuda:0 etc. auto 表示自动选择可用的 GPU，否则使用 CPU
    ckpt_interval: 10 # 模型保存间隔轮数，0 表示只保存最后一个模型
    save_best_with: min_val_loss # 保存最佳模型的依据指标
    loss: # 损失函数配置
      type: focal # 损失函数类型，可选值：ce, weighted_ce, focal, label_smoothing
      # ce: 标准交叉熵损失
      # weighted_ce: 加权交叉熵（处理类别不平衡）
      # focal: 聚焦损失（关注难分样本）
      # label_smoothing: 标签平滑损失（防止过拟合）

      # 类别权重配置（可选，用于处理类别不平衡）
      class_weights: null # 如果为null则使用均等权重，否则指定每个类别的权重
      # 例如处理不平衡: [2.0, 1.0, 1.0] 表示第0类权重为2倍

      # 通道权重配置（可选，为不同输出通道分配不同权重）
      # 例如5个手指的权重：thumb往往更重要
      channel_weights: null
      # 如果为null则使用均等权重，否则指定每个通道的权重
      # 例如: [0.25, 0.2, 0.2, 0.2, 0.15] 表示 [thumb, index, middle, ring, pinky]

      # 损失函数特定参数
      # focal loss 的 gamma 参数
      focal:
        gamma: 2.0 # gamma越大越关注难分样本，通常2.0效果最好

      # label smoothing 的 smoothing 参数
      label_smoothing:
        smoothing: 0.1 # 平滑系数，通常0.1效果最好

    optim:
      type: adamw # 优化器类型，可选值：sgd, adam, adamw
      learning_rate: 0.001 # 学习率
      weight_decay: 0.0001 # 权重衰减
      sgd:
        momentum: 0.9 # 动量参数
        nesterov: true # 是否启用 Nesterov 动量
      adam:
        betas: [0.9, 0.999] # Adam 优化器
      adamw:
        betas: [0.9, 0.999] # AdamW 优化

    policies:
      # 早停配置
      early_stopping: # 早停策略
        enabled: true # 是否启用早停
        patience: 10 # 容忍不改善的轮数
        min_delta: 0.0001 # 最小改善阈值

      # 学习率调度配置
      lr_scheduler: # 学习率调度策略
        enabled: true # 是否启用学习率调度
        type: plateau # 调度器类型：step, exponential, cosine, plateau, warmup
        # step: 每N轮减少学习率
        # exponential: 指数衰减
        # cosine: 余弦退火
        # plateau: 性能不改善时减少
        # warmup: 预热后指数衰减

        # step调度器参数
        step_size: 10 # 每多少轮减少一次
        step_gamma: 0.1 # 减少的倍数

        # exponential调度器参数
        exp_gamma: 0.95 # 指数衰减因子

        # cosine调度器参数
        cosine_T_max: 100 # 最大轮数
        cosine_eta_min: 0 # 最小学习率

        # plateau调度器参数
        plateau_factor: 0.1 # 减少的倍数
        plateau_patience: 5 # 容忍不改善的轮数

        # warmup调度器参数
        warmup_epochs: 5 # 预热轮数
        total_epochs: 100 # 总轮数

      # 预热学习率配置
      warmup: # 预热策略
        enabled: true # 是否启用预热
        warmup_epochs: 5 # 预热轮数
        total_epochs: 100 # 总轮数
        method: linear # 预热方式：linear, exponential
        decay_method: cosine # 衰减方式：cosine, linear, step

      # 梯度裁剪配置
      gradient_clip: # 梯度裁剪策略
        enabled: true # 是否启用梯度裁剪
        max_norm: 1.0 # 最大梯度范数
        norm_type: 2.0 # 范数类型

      # 权重平均配置
      swa: # Stochastic Weight Averaging
        enabled: true # 是否启用权重平均
        swa_start: 80 # 从第几轮开始进行权重平均
        swa_freq: 5 # 权重平均的频率
        update_bn: true # 是否更新批规范化统计

    visualization:
      backend: tensorboard # 可视化后端，可选值：none, tensorboard
      interval: 5 # 可视化间隔轮数
      cn_font: ./assets/fonts/LXGWWenKaiMono-Regular.ttf # 中文字体路径，用于支持中文显示
      info: # 可视化信息列表
        - loss
        - accuracy
        - precision
        - recall
        - f1_score
        - confusion_matrix

  eval:
    batch_size: 32 # 评估批量大小
    metrics: # 评估指标列表
      - loss
      - accuracy
      - precision
      - recall
      - f1_score
      - confusion_matrix

model: # 模型配置
  pretrain: null # 预训练模型路径，若为 null 则不加载预训练模型 (TODO)
  encoder:
    type: transformer # 编码器类型，可选值：cnn, resnet, lstm, transformer, hmm etc
    activation: relu
    cnn:
      layers: [64, 128, 256] # CNN层配置，每个数字表示该层的输出通道数
      kernel_sizes: [3, 3, 3] # 卷积核大小列表
      strides: [1, 1, 1] # 步幅列表
    resnet:
      depth: 34 # ResNet深度，可选值：18, 34
    lstm:
      append_mode: true # 是否启用LSTM层在CNN/ResNet之后, 否则单独使用LSTM作为编码器
      hidden_size: 128 # LSTM隐藏层大小
      num_layers: 2 # LSTM层数
    transformer:
      num_heads: 4 # 多头注意力头数
      num_layers: 2 # Transformer层数
      dim_feedforward: 256 # 前馈网络维度
    hmm: # 隐马尔可夫模型配置
      num_states: 5 # 隐状态数量
      covariance_type: diag # 协方差类型，可选值：full, tied, diag, spherical

  classifier:
    type: fc # 分类器类型，可选值：fc, svm
    fc:
      hidden_sizes: [128, 64] # 全连接层隐藏层大小列表
    svm:
      C: 1.0 # SVM正则化参数

# 仿真配置
simulation:
  enabled: true # 是否启用仿真模式，开启后将会把采样结果/预测结果发送给 Unity 环境
  host: 127.0.0.1
  port: 8888 # 仿真服务器端口
  struct: A<ch1><ch2><ch3><ch4><ch5>B # 把对应位置替换为输出分类编号

# 数据源配置
review:
  file_path: ./data/default/sample.npz # 已采样数据文件路径，仅在 data.source 为 review 时有效
  loop: true # 是否循环回放数据
  interval: 0.05 # 数据回放间隔，单位秒

generate:
  type: sine # 生成数据类型，可选值：default, sine, square # default 则随机选取纯 sine 生成数据 # sine 和 square 则根据下方参数生成对应波形数据
  frequency: # 频率分量列表，单位Hz，仅在 type 为 sine 或 square 时有效
    - [5, 10, 17] # CH1 频率分量
    - [10, 20, 30] # CH2 频率分量
    - [15, 25, 35] # CH3 频率分量
    - [20, 30, 40] # CH4 频率分量
    - [25, 35, 45] # CH5 频率分量
    - [30, 40, 50] # CH6 频率分量
    - [35, 45, 55] # CH7 频率分量
    - [40, 50, 60] # CH8 频率分量
  amplitude:
    - [1.0, 0.5, 0.2] # CH1 振幅列表
    - [1.0, 0.5, 0.2] # CH2 振幅列表
    - [1.0, 0.5, 0.2] # CH3 振幅列表
    - [1.0, 0.5, 0.2] # CH4 振幅列表
    - [1.0, 0.5, 0.2] # CH5 振幅列表
    - [1.0, 0.5, 0.2] # CH6 振幅列表
    - [1.0, 0.5, 0.2] # CH7 振幅列表
    - [1.0, 0.5, 0.2] # CH8 振幅列表
  noise_level: 0.05 # 噪声水平，控制随机噪声的幅度
  interval: 0.05 # 数据生成间隔，单位秒

esp32:
  port: # 端口设置，用于通信
    discover: 5005 # 发现端口
    register: 5006 # 注册端口
    data: 5007 # 数据传输端口
  adc: # ADC配置，用于计算真实电压
    vref: 2.4 # 单位V
    gain: 12 # 单位dB
    bitwidth: 24 # ADC位宽
  timeout: 10 # 无数据超时时间，超时需重新注册，单位秒
  amplifier: 1e4 # 原始数据放大倍数，1e6 单位为 uV, 1e4 为 0.1mV, 1e3 为 mV

export:
  enabled: true # 是否启用模型导出
  format: onnx # 导出格式，可选值：onnx, torchscript
  onnx:
    opset_version: 18 # ONNX opset 版本（推荐 18+，支持最新特性）
    dynamic_axes: 
      enabled: true # 是否启用动态轴（支持可变批量大小和时间步）
      # 注意：动态轴配置仅用于文档说明，实际使用简化版本
      # 简化版本会对 batch_size 维度启用动态轴
  torchscript:
    method: trace # 导出方法，可选值：trace, script
    # trace: 通过追踪执行路径导出（推荐，适用于大多数模型）
    # script: 通过分析代码导出（适用于包含控制流的模型）
    optimize: true # 是否优化模型（启用推理优化）


